modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="memetallica"
version="1.0.0"
displayName="memetallica"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="aidan, MCreator"

[[dependencies.memetallica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




